<?php

namespace Database\Seeders;

use App\Models\Pregnancy;
use App\Models\User;
use Illuminate\Database\Seeder;

class PregnancySeeder extends Seeder
{
    public function run(): void
    {
        $users = User::where('role', 'user')->get();

        $seedData = [
            [
                'nama_istri'   => 'Siti Aminah',
                'nama_suami'   => 'Budi Santoso',
                'umur_istri'   => 28,
                'umur_suami'   => 30,
                'alamat'       => 'Jl. Mawar No. 5, Bandung',
                'no_telpon'    => '0812-3456-7890',
                'gravida'      => 2,
                'partus'       => 1,
                'abortus'      => 0,
                'hpht'         => now()->subWeeks(20),
                'tanggal'      => now(),
                'pemeriksaan'  => 'Tinggi fundus 20 sm, LILA 28 cm, Letak longitudinal cephalic, jantung janin 140 x/menit',
                'keluhan'      => 'Mual pagi hari, nyeri pinggul ringan',
                'terapi'       => 'Tablet Fe 1x1, Vitamin B1 1x1',
                'keterangan'   => 'Kontrol rutin 1 bulan lagi.',
            ],
            [
                'nama_istri'   => 'Dewi Kusuma',
                'nama_suami'   => 'Ahmad Fauzi',
                'umur_istri'   => 32,
                'umur_suami'   => 35,
                'alamat'       => 'Jl. Kenanga No. 12, Surabaya',
                'no_telpon'    => '0856-9876-5432',
                'gravida'      => 3,
                'partus'       => 2,
                'abortus'      => 0,
                'hpht'         => now()->subWeeks(32),
                'tp'           => now()->addWeeks(8),
                'tanggal'      => now(),
                'pemeriksaan'  => 'Tinggi fundus 28 sm, LILA 30 cm, Letak longitudinal cephalic',
                'keluhan'      => 'Sesak napas ringan, kaki bengkak',
                'terapi'       => 'Tablet Ca 2x1, parasetamol sesuai kebutuhan',
                'keterangan'   => 'Kontrol 2 minggu lagi. Disarankan istirahat cukup.',
            ],
            [
                'nama_istri'   => 'Rina Wati',
                'nama_suami'   => null,
                'umur_istri'   => 25,
                'umur_suami'   => null,
                'alamat'       => 'Jl. Melati No. 8, Yogyakarta',
                'no_telpon'    => '0897-1234-5678',
                'gravida'      => 1,
                'partus'       => 0,
                'abortus'      => 0,
                'hpht'         => now()->subWeeks(12),
                'tp'           => now()->addWeeks(28),
                'tanggal'      => now(),
                'pemeriksaan'  => 'Tinggi fundus 14 sm, LILA 24 cm, jantung janin 148 x/menit',
                'keluhan'      => 'Mual, muntah, mudah lelah',
                'terapi'       => 'Vitamin B6 2x1, Tablet Fe 1x1',
                'keterangan'   => 'Primipara, edukasi bahaya kehamilan.',
            ],
            [
                'nama_istri'   => 'Ani Suryani',
                'nama_suami'   => 'Eko Prasetyo',
                'umur_istri'   => 30,
                'umur_suami'   => 33,
                'alamat'       => 'Jl. Anggrek No. 3, Semarang',
                'no_telpon'    => '0878-3344-5566',
                'gravida'      => 4,
                'partus'       => 3,
                'abortus'      => 0,
                'hpht'         => now()->subWeeks(38),
                'tp'           => now()->addWeeks(2),
                'tanggal'      => now(),
                'pemeriksaan'  => 'Tinggi fundus 34 sm, LILA 32 cm,Letak longitudinal cephalic, NST reactive',
                'keluhan'      => 'Nyeri kontraksi braxton hicks, sulit tidur malam',
                'terapi'       => 'Konsumsi air hangat sebelum tidur',
                'keterangan'   => 'Hamil 38 minggu, siap persalinan.',
            ],
            [
                'nama_istri'   => 'Dina Rahayu',
                'nama_suami'   => 'Rahmat Hidayat',
                'umur_istri'   => 27,
                'umur_suami'   => 29,
                'alamat'       => 'Jl. Teratai No. 15, Medan',
                'no_telpon'    => '0821-9988-7766',
                'gravida'      => 2,
                'partus'       => 1,
                'abortus'      => 0,
                'hpht'         => now()->subWeeks(24),
                'tp'           => now()->addWeeks(12),
                'tanggal'      => now(),
                'pemeriksaan'  => 'Tinggi fundus 24 sm, LILA 29 cm, Letak longitudinal cephalic, jantung janin 138 x/menit',
                'keluhan'      => 'Sakit kepala, pusing berulang',
                'terapi'       => 'Paracetamol 500mg jika diperlukan',
                'keterangan'   => 'Kontrol 4 minggu lagi.',
            ],
            [
                'nama_istri'   => 'Lina Marlina',
                'nama_suami'   => 'Agus Setiawan',
                'umur_istri'   => 35,
                'umur_suami'   => 38,
                'alamat'       => 'Jl. Cempaka No. 9, Palembang',
                'no_telpon'    => '0853-1122-3344',
                'gravida'      => 3,
                'partus'       => 2,
                'abortus'      => 0,
                'hpht'         => now()->subWeeks(28),
                'tp'           => now()->addWeeks(10),
                'tanggal'      => now(),
                'pemeriksaan'  => 'Tinggi fundus 26 sm, LILA 30 cm, Letak longitudinal cephalic',
                'keluhan'      => 'Nyeri pinggang, produksi',
                'terapi'       => 'Vitamin E 1x1, Tablet Ca 2x1',
                'keterangan'   => 'Rekomendasi senam hamil setiap hari.',
            ],
            [
                'nama_istri'   => 'Putri Handayani',
                'nama_suami'   => 'Bambang Kusumo',
                'umur_istri'   => 26,
                'umur_suami'   => 31,
                'alamat'       => 'Jl. Flamboyan No. 2, Malang',
                'no_telpon'    => '0813-5566-7788',
                'gravida'      => 1,
                'partus'       => 0,
                'abortus'      => 0,
                'hpht'         => now()->subWeeks(16),
                'tp'           => now()->addWeeks(24),
                'tanggal'      => now(),
                'pemeriksaan'  => 'Tinggi fundus 16 sm, LILA 25 cm, jantung janin 145 x/menit',
                'keluhan'      => 'Mual muntah hebat, kehilangan nafsu makan',
                'terapi'       => 'Vitamin B6 2x1, Vitamin C 1x1',
                'keterangan'   => 'Trimester 1, waspadi preeklampsia.',
            ],
            [
                'nama_istri'   => 'Yuliana',
                'nama_suami'   => null,
                'umur_istri'   => 38,
                'umur_suami'   => null,
                'alamat'       => 'Jl. Dahlia No. 21, Makassar',
                'no_telpon'    => '0822-3344-5566',
                'gravida'      => 5,
                'partus'       => 4,
                'abortus'      => 1,
                'hpht'         => now()->subWeeks(30),
                'tp'           => now()->addWeeks(8),
                'tanggal'      => now(),
                'pemeriksaan'  => 'Tinggi fundus 30 sm, LILA 31 cm, Letak longitudinal cephalic',
                'keluhan'      => 'Nyeri otot badan, mudah lelah',
                'terapi'       => 'Vitamin B Kompleks 1x1, Tablet Fe 2x1',
                'keterangan'   => 'Kontrol minggu depan.',
            ],
            [
                'nama_istri'   => 'Hasanah',
                'nama_suami'   => 'Zainal Abidin',
                'umur_istri'   => 29,
                'umur_suami'   => 32,
                'alamat'       => 'Jl. Mangga No. 7, Denpasar',
                'no_telpon'    => '0857-6677-8899',
                'gravida'      => 2,
                'partus'       => 1,
                'abortus'      => 0,
                'hpht'         => now()->subWeeks(18),
                'tp'           => now()->addWeeks(22),
                'tanggal'      => now(),
                'pemeriksaan'  => 'Tinggi fundus 18 sm, LILA 27 cm, Letak longitudinal cephalic, jantung janin 142 x/menit',
                'keluhan'      => 'Sering kencing, nyeri pinggul',
                'terapi'       => 'Tablet Fe 1x1, Vitamin C 1x1',
                'keterangan'   => 'Kontrol bulanan.',
            ],
            [
                'nama_istri'   => 'Sari Dewi',
                'nama_suami'   => 'Fajar Nugroho',
                'umur_istri'   => 24,
                'umur_suami'   => 27,
                'alamat'       => 'Jl. Jeruk No. 4, Balikpapan',
                'no_telpon'    => '0814-2233-4455',
                'gravida'      => 1,
                'partus'       => 0,
                'abortus'      => 0,
                'hpht'         => now()->subWeeks(10),
                'tp'           => now()->addWeeks(30),
                'tanggal'      => now(),
                'pemeriksaan'  => 'Tinggi fundus 12 sm, LILA 23 cm, jantung janin 150 x/menit',
                'keluhan'      => 'Mual muntah hebat, kehilangan nafsu makan',
                'terapi'       => 'Vitamin B6 2x1, Daun sirih',
                'keterangan'   => 'Trimester 1, waspadi preeklampsia.',
            ],
        ];

        foreach ($seedData as $data) {
            $data['user_id'] = $users->random()->id;

            Pregnancy::create($data);
        }
    }
}
